### PR TITLE
Add more details for compatibility and performances

### PR DESCRIPTION
**Pull request by robertoperuzzo**

### CODE REVIEW

**Review by rfay — COMMENTED** [review]
This would be slightly better with an explanation of what the links are so people don't have to click through to find out what you mean, but now it has the links. 

Maybe they'll have arm64 someday, or maybe we'll figure out a reliable way to use the amd64 with arm64. I'm pretty sure with tweaking that this could be made to work on macOS 13.4 Apple Silicon with the right settings on orbStack, Docker Desktop, and Colima. But *just* the right settings.

**Comment by robertoperuzzo** [comment]
> This would be slightly better with an explanation of what the links are so people don't have to click through to find out what you mean, but now it has the links.
> 
> Maybe they'll have arm64 someday, or maybe we'll figure out a reliable way to use the amd64 with arm64. I'm pretty sure with tweaking that this could be made to work on macOS 13.4 Apple Silicon with the right settings on orbStack, Docker Desktop, and Colima. But _just_ the right settings.

You're right. I added some details. 
Thanks.

**Comment by rfay** [comment]
Thanks, don't forget to do a release when you have everything you want sorted. 

I don't recommend automatic merging, I'll turn that off.

**Review by rfay — APPROVED** [review]
Looks great, thanks.

**Pull request merged**
